# Generated by Django 5.2 on 2025-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_update_interval_devicedata_power_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
