# Generated by Django 5.2 on 2025-05-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_device_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceshare',
            name='permission',
            field=models.CharField(default='view', max_length=20),
        ),
    ]
